name: CICD Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Main:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore Nuget Packages
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release src/NumericExtensions/NumericExtensions.csproj --output .
    - name: Push Nuget Package
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGETAPIKEY}} --skip-duplicate
